### PR TITLE
just a few typo fixes, nothing major

### PR DESCRIPTION
**Pull request by corinnebosley**
Conda-gitenv is so cool! I didn't really understand what it was before, and now I do, and it's awesome.

Anyway, this is just a few typo fixes which I felt I had to apply to appease my OCD nature.  I may make some alterations to a few sections of the readme later on (I found the first paragraph and the notes section a little confusing) but for now these are purely cosmetic changes.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@pelson @bjlittle I am hoping to get these teeny tiny changes merged pretty quick.  It's just typo fixes is all.

**Comment by corinnebosley** [comment]
Right well that's not good is it? This was supposed to be simple.

**Comment by corinnebosley** [comment]
Well I don't know what's going on here.  When I run that test locally it passes.  I'll keep digging...

**Comment by pelson** [comment]
The error is something like:

```
DEBUG git.cmd:execute(719): Popen(['git', 'checkout', 'manifest/example_env'], cwd=/home/travis/build/SciTools/conda-gitenv/conda_gitenv/tests/integration/sample_repos/labelled_tags, universal_newlines=False, shell=None)
Traceback (most recent call last):
  File "/home/travis/conda/bin/conda-gitenv", line 11, in <module>
    load_entry_point('conda-gitenv==0.3.2.dev4+head.detached.at.fetch.head', 'console_scripts', 'conda-gitenv')()
  File "/home/travis/conda/lib/python2.7/site-packages/conda_gitenv-0.3.2.dev4+head.detached.at.fetch.head-py2.7.egg/conda_gitenv/cli.py", line 22, in main
    return args.function(args)
  File "/home/travis/conda/lib/python2.7/site-packages/conda_gitenv-0.3.2.dev4+head.detached.at.fetch.head-py2.7.egg/conda_gitenv/label_tag.py", line 67, in handle_args
    create_tracking_branches(repo)
  File "/home/travis/conda/lib/python2.7/site-packages/conda_gitenv-0.3.2.dev4+head.detached.at.fetch.head-py2.7.egg/conda_gitenv/resolve.py", line 105, in create_tracking_branches
    heads_to_skip = ['HEAD'] + [branch.name for branch in repo.branches]
  File "/home/travis/conda/lib/python2.7/site-packages/git/repo/base.py", line 267, in heads
    return Head.list_items(self)
  File "/home/travis/conda/lib/python2.7/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/home/travis/conda/lib/python2.7/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/home/travis/conda/lib/python2.7/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

It is a concern, but not for this PR.

**Comment by pelson** [comment]
Thanks @corinnebosley!

**Pull request merged**
